name: analysis

on:
  schedule:
    - cron: '0 0 21 * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install build-essential
        pip install -r requirements_analysis.txt

    - name: Run script
      run: |
        python test.py
    - name: Add and commit
      uses: EndBug/add-and-commit@v9
      with:
        author_name: GitHub Actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "chore: Update file"
        add: "*.csv *.png *.pkl *.geojson"
