name: analysis

on:
  schedule:
    - cron: '0 0 21 * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade cython
        sed -i '1i# distutils: language=c++' 
        pip install -r requirements_analysis.txt

    - name: Run script
      run: |
        python test.py
